name: 03 - Workflow - Runners

on: push

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: echo "This jobs runs on ubuntu runner. Runner OS $RUNNER_OS"
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show OS
        shell: bash
        run: echo "This jobs runs on Windows runner. Runner OS $RUNNER_OS"
  mac-echo:
    runs-on: macos-latest
    steps:
      - name: Show OS
        run: echo "This jobs runs on MacOS runner. Runner OS $RUNNER_OS"
