name: 08 - Using Variables

on: 
  push:
  workflow_dispatch:

env:
    WORKFLOW_VAR: "I am a workflow env var"
    OVERWRITTEN: "I am overwritten at workflow level"

jobs: 
    echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: "I am a job env var"
            OVERWRITTEN: "I am overwritten at job level"
        steps:
            - name: Print Env Variables
              env:
                STEP_VAR: "I am a step env var"
                STEP_VAR2: "I am another step env var"
              run: |
                 echo "Step env var: ${{ env.STEP_VAR }}"
                 echo "Step env var2: ${{ env.STEP_VAR2 }}"
                 echo "Job env var: ${{ env.JOB_VAR }}"
                 echo "Workflow env var: ${{ env.WORKFLOW_VAR }}"
                 echo "Overwritten env var: ${{ env.OVERWRITTEN }}"
            - name: "Overwrite job variable"
              env:
                OVERWRITTEN: "I am overwritten at step level"
              run: |
                 echo "Overwritten: ${{ env.OVERWRITTEN }}"

