name: 10 - Controlling Execution Flow

on:
    workflow_dispatch:
      inputs: 
        pass-unit-tests:
          type: boolean
          description: Whether unit tests will pass or not
          default: true

jobs:
  lint-build:
    runs-on: ubuntu_latest
    steps:
        - name: Lint and build
          run: echo "Linting and building project"
  unit-tests:
    runs-on: ubuntu_latest
    steps:
        - name: Running unit tests
          run: echo "Running tests..."
        - name: Failing tests
          if: ${{ !inputs.pass-unit-tests }}
          run: exit 1
  deploy-nonprod:
    runs-on: ubuntu_latest
    needs: 
        - lint-build
        - unit-tests
    steps:
        - name: Deploying to non-prod
          run: echo "Deploying to non-prod..."
  e2e-tests:
    runs-on: ubuntu_latest
    needs: 
        - deploy-nonprod
    steps:
        - name: Running E2E tests
          run: echo "Running E2E tests"
  load-tests:
    runs-on: ubuntu_latest
    needs: 
        - deploy-nonprod
    steps:
        - name: Running load tests
          run: echo "Running load tests"
  deploy-prod:
    runs-on: ubuntu_latest
    needs: 
        - e2e-tests
        - load-tests
    steps:
        - name: Deploying to prod
          run: echo "Deploying to prod..."
    