name: 11 - Working with Inputs

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: Skip deployment and only print build output
        default: false
      target: 
        type: environment
        options:
          - Prod
          - Staging
        required: true
        description: Which environment the workflow will target
      tag:
        type: choice
        options:
          - V1
          - V2
          - V3
        default: V3
        description: Release from which to build and deploy

jobs:
  echo:
    runs-on: ubuntu_latest
    steps:
        - name: Build
          run: echo "Building from tag ${{ inputs.tag }}"
  deploy:
    runs-on: ubuntu_latest
    if: ${{ inputs }}
    environment: ${{ inputs.target }}
    steps:
        - name: Deploy
          run: Deploying to ${{ inputs.target }}


